/* Library source generated by funcmap
   (Copyright (c) 2003 Lorenzo J. Lucchini, <ljlbox@tiscalinet.it>)

   Every library function saves the address to resume userland execution from
   into HL, then loads the system call number into A, and then makes the call
   by means of a RST08 instruction. */


/* Declarations */

void* MemoryAllocate(unsigned int, memType);
void MemoryFree(void*);
lock LockCreate();
void LockObtain(lock Handle);
void LockRelease(lock Handle);

/* Definitions */ 

void* MemoryAllocate(unsigned int, memType) {
    _asm
    pop hl
    ld a,#0x00
    rst 0x08
    _endasm;
}

void MemoryFree(void*) {
    _asm
    pop hl
    ld a,#0x01
    rst 0x08
    _endasm;
}

lock LockCreate() {
    _asm
    pop hl
    ld a,#0x02
    rst 0x08
    _endasm;
}

void LockObtain(lock Handle) {
    _asm
    pop hl
    ld a,#0x03
    rst 0x08
    _endasm;
}

void LockRelease(lock Handle) {
    _asm
    pop hl
    ld a,#0x04
    rst 0x08
    _endasm;
}
